<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Tous les items du fichier Canevas_INVENTAIRE.xlsx sont des ARTICLES
 * (equipements) : chacun dispose d'un numero d'inventaire individuel IS-XXXX.
 *
 * Regle statut :
 *   Reforme   => lieu d'affectation = "Reforme"
 *   Disponible => en hangar / magasin / stock (non encore affecte)
 *   Affecte    => dans une salle operationnelle
 *
 * Les CONSOMMABLES (geres par quantite de stock) ne figurent pas dans ce
 * fichier Excel ; alimentez-les via ConsommableSeeder.
 */
class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        // [numero_reference, code_ancien, designation, statut, code_categorie]
        $articles = [
            ['IS0474', '4903', 'Appareil Numérique Samsung ES 73', 'Réformé', 'CAT_PHOTOCOPIEUR'],
            ['IS0042', '4375', 'Appareil Photocopieur REX ROTARY 415', 'Réformé', 'CAT_PHOTOCOPIEUR'],
            ['IS1159', '3130', 'Armoire basse en bois noir avec deux portes battant 110x55x75 avec 1 tiroir et 2 tablettes et serrures 75x95x43 cm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1671', '4200', 'Armoire haute métallique gris perle à portes battantes Dimens 1970mm, 1200mn, profondeur 450mm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1672', '4201', 'Armoire haute métallique gris perle à portes battantes Dimens 1970mm, 1200mn, profondeur 450mm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1673', '4202', 'Armoire haute métallique gris perle à portes battantes Dimens 1970mm, 1200mn, profondeur 450mm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1674', '4203', 'Armoire haute métallique gris perle à portes battantes Dimens 1970mm, 1200mn, profondeur 450mm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1675', '4204', 'Armoire haute métallique gris perle à portes battantes Dimens1970mm, 1200mn, profondeur 450mm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1676', '4205', 'Armoire haute métallique gris perle à portes battantesDimens1970mm, 1200mn, profondeur 450mm', 'Affecté', 'CAT_ARMOIRE'],
            ['IS0701', '5107', 'Armoire métallique avec portes pliante L120xH120×P45 avec serrure', 'Affecté', 'CAT_ARMOIRE'],
            ['IS0702', '5108', 'Armoire métallique avec portes pliante L120xH120×P45 avec serrure', 'Affecté', 'CAT_ARMOIRE'],
            ['IS0703', '5109', 'Armoire métallique avec portes pliante L120xH120×P45 avec serrure', 'Affecté', 'CAT_ARMOIRE'],
            ['IS0185', '4509', 'Armoire métallique haute à 2 portes battantes avec serrure équipée de 4 étagères réglables (LXPXH en mm : 940x450x1980)', 'Affecté', 'CAT_ARMOIRE'],
            ['IS0186', '4510', 'Armoire métallique haute à 2 portes battantes avec serrure équipée de 4 étagères réglables (LXPXH en mm : 940x450x1980)', 'Affecté', 'CAT_ARMOIRE'],
            ['IS0187', '4511', 'Armoire moyenne en bois, série KAMOS à 2 portes battantes (LXPXH en mm : 900x450x1340)', 'Affecté', 'CAT_ARMOIRE'],
            ['1367/SEGMA', null, 'ARMOIRE REFRIGEREE PROFESSIONNELLE POSITIVE', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1047', '3026', 'Armoires fortes 2mx1m avec combinaison et 4 étagères modulables', 'Affecté', 'CAT_ARMOIRE'],
            ['IS1532', '4048', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1533', '4049', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1534', '4050', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1535', '4051', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1536', '4052', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1538', '4053', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1539', '4054', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1540', '4055', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS1541', '4056', 'Arrosoir en plastique, gris, 13 litres', 'Réformé', 'CAT_ARROSOIR'],
            ['IS0234', '4632', 'Asperseur escamotable S.R.S', 'Réformé', 'CAT_ASPERSEUR_ESCAMOTABL'],
            ['IS0235', '4633', 'Asperseur escamotable S.R.S', 'Réformé', 'CAT_ASPERSEUR_ESCAMOTABL'],
            ['IS0236', '4634', 'Asperseur escamotable S.R.S', 'Réformé', 'CAT_ASPERSEUR_ESCAMOTABL'],
            ['IS0197', '4523', 'Atomiseur à essence à dos 3 WF – 3A', 'Disponible', 'CAT_ATOMISEUR'],
            ['IS1253', '3551', 'Atomiseur à moteur à dos pour produit liquide MD 150 DX', 'Réformé', 'CAT_ATOMISEUR'],
            ['IS1282', '3609', 'Auge de maçon en caoutchouc', 'Réformé', 'CAT_AUGE_DE_MA_ON'],
            ['IS0748', '5150', 'Balai à gazon 24 dents', 'Disponible', 'CAT_BALAI_GAZON'],
            ['IS0749', '5151', 'Balai à gazon 24 dents', 'Disponible', 'CAT_BALAI_GAZON'],
            ['IS0750', '5152', 'Balai à gazon 24 dents', 'Disponible', 'CAT_BALAI_GAZON'],
            ['IS0751', '5153', 'Balai à gazon 24 dents', 'Disponible', 'CAT_BALAI_GAZON'],
            ['IS0752', '5154', 'Balai à gazon 24 dents', 'Disponible', 'CAT_BALAI_GAZON'],
            ['IS1528', '4043', 'Balai à gazon avec manche Wolf, 50cm, 22 dents plates Réf. UE Wolf', 'Réformé', 'CAT_BALAI_GAZON'],
            ['IS1529', '4044', 'Balai à gazon avec manche Wolf, 50cm, 22 dents plates Réf. UE Wolf', 'Réformé', 'CAT_BALAI_GAZON'],
            ['IS1530', '4045', 'Balai à gazon avec manche Wolf, 50cm, 22 dents plates Réf. UE Wolf', 'Affecté', 'CAT_BALAI_GAZON'],
            ['IS1531', '4046', 'Balai à gazon avec manche Wolf, 50cm, 22 dents plates Réf. UE Wolf', 'Affecté', 'CAT_BALAI_GAZON'],
            ['IS0022', '801', 'Balance 10Kg', 'Réformé', 'CAT_BALANCE'],
            ['IS0011', '800', 'Balance 200Kg', 'Réformé', 'CAT_BALANCE'],
            ['IS0432', '1480', 'Bêche', 'Réformé', 'CAT_B_CHE'],
            ['IS0443', '1481', 'Bêche', 'Réformé', 'CAT_B_CHE'],
            ['IS0455', '1482', 'Bêche', 'Réformé', 'CAT_B_CHE'],
            ['IS0466', '1483', 'Bêche', 'Réformé', 'CAT_B_CHE'],
            ['IS0477', '1484', 'Bêche', 'Réformé', 'CAT_B_CHE'],
            ['IS1403', '3812', 'Bêche avec manche béquille 1m avec repose pied – hauteur du plateau 28cm ABT Wolf ou son équivalent', 'Disponible', 'CAT_B_CHE'],
            ['IS1404', '3813', 'Bêche avec manche béquille 1m avec repose pied – hauteur du plateau 28cm ABT Wolf ou son équivalent', 'Disponible', 'CAT_B_CHE'],
            ['IS1406', '3814', 'Bêche avec manche béquille 1m avec repose pied – hauteur du plateau 28cm ABT Wolf ou son équivalent', 'Disponible', 'CAT_B_CHE'],
            ['IS1407', '3815', 'Bêche avec manche béquille 1m avec repose pied – hauteur du plateau 28cm ABT Wolf ou son équivalent', 'Disponible', 'CAT_B_CHE'],
            ['IS1408', '3816', 'Bêche avec manche béquille 1m avec repose pied – hauteur du plateau 28cm ABT Wolf ou son équivalent', 'Disponible', 'CAT_B_CHE'],
            ['IS1409', '3817', 'Bêche avec manche béquille 1m avec repose pied – hauteur du plateau 28cm ABT Wolf ou son équivalent', 'Disponible', 'CAT_B_CHE'],
            ['IS1294', '3664', 'Bêche avec manche béquille 1m avec repose pied Wolf ABT', 'Disponible', 'CAT_B_CHE'],
            ['IS1296', '3665', 'Bêche avec manche béquille 1m avec repose pied Wolf ABT', 'Disponible', 'CAT_B_CHE'],
            ['IS1297', '3666', 'Bêche avec manche béquille 1m avec repose pied Wolf ABT', 'Disponible', 'CAT_B_CHE'],
            ['IS1298', '3667', 'Bêche avec manche béquille 1m avec repose pied Wolf ABT', 'Disponible', 'CAT_B_CHE'],
            ['IS1299', '3668', 'Bêche avec manche béquille 1m avec repose pied Wolf ABT', 'Disponible', 'CAT_B_CHE'],
            ['IS0488', '1493', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0499', '1494', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0510', '1495', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0521', '1496', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0532', '1497', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0543', '1498', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0554', '1499', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0566', '1500', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0577', '1501', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0588', '1502', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0599', '1503', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0610', '1504', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0621', '1505', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0632', '1506', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0643', '1507', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0654', '1508', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0665', '1509', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0677', '1510', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0688', '1511', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0699', '1512', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0710', '1513', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0721', '1514', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0732', '1515', 'Binette', 'Affecté', 'CAT_BINETTE'],
            ['IS0743', '1516', 'Binette', 'Affecté', 'CAT_BINETTE'],
            ['IS0754', '1517', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0765', '1518', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0776', '1519', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS0788', '1520', 'Binette', 'Réformé', 'CAT_BINETTE'],
            ['IS1604', '4117', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1605', '4118', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1606', '4119', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1607', '4120', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1608', '4121', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1609', '4122', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1610', '4123', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1611', '4124', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1612', '4125', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1613', '4126', 'Binette Réf. Wolf HWM 15 avec manche ZM 30', 'Disponible', 'CAT_BINETTE'],
            ['IS1335', '3723', 'Brouette 20/10', 'Réformé', 'CAT_BROUETTE'],
            ['IS1336', '3724', 'Brouette 20/10', 'Réformé', 'CAT_BROUETTE'],
            ['IS0753', '5155', 'Brouette 20/20', 'Réformé', 'CAT_BROUETTE'],
            ['IS0755', '5156', 'Brouette 20/20', 'Réformé', 'CAT_BROUETTE'],
            ['IS0756', '5157', 'Brouette 20/20', 'Réformé', 'CAT_BROUETTE'],
            ['IS0757', '5158', 'Brouette 20/20', 'Réformé', 'CAT_BROUETTE'],
            ['IS0758', '5159', 'Brouette 20/20', 'Réformé', 'CAT_BROUETTE'],
            ['IS1214', '3408', 'Brouette avec Roue 20/10', 'Réformé', 'CAT_BROUETTE'],
            ['IS1215', '3409', 'Brouette avec Roue 20/10', 'Réformé', 'CAT_BROUETTE'],
            ['IS1216', '3410', 'Brouette avec Roue 20/10', 'Réformé', 'CAT_BROUETTE'],
            ['IS1217', '3411', 'Brouette avec Roue 20/10', 'Réformé', 'CAT_BROUETTE'],
            ['IS0109', '4440', 'Brouette en tole de 20/10 avec roue', 'Réformé', 'CAT_BROUETTE'],
            ['IS0111', '4441', 'Brouette en tole de 20/10 avec roue', 'Réformé', 'CAT_BROUETTE'],
            ['IS0112', '4442', 'Brouette en tole de 20/10 avec roue', 'Réformé', 'CAT_BROUETTE'],
            ['IS0001', '398', 'Bureau de classe à 2 tiroirs 118/58cm', 'Réformé', 'CAT_BUREAU'],
            ['IS0002', '399', 'Bureau de classe à 2 tiroirs 118/58cm', 'Réformé', 'CAT_BUREAU'],
            ['IS0204', '4529', 'Bureau en bois, série KAMOS (LXPXH en mm : 1800x800x720)', 'Affecté', 'CAT_BUREAU'],
            ['IS1043', '3019', 'Bureau pour cadre 1,60x0,80 en bois stratifié couleur noir + caisson à 2T + serrure', 'Affecté', 'CAT_BUREAU'],
            ['IS1044', '3020', 'Bureau pour cadre 1,60x0,80 en bois stratifié couleur noir + caisson à 2T + serrure', 'Affecté', 'CAT_BUREAU'],
            ['IS0548', '4970', 'Bureau pour cadre, plateau en Bois, double face, piètements métalliques réglable, Dim. 1600×800×750, 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0549', '4971', 'Bureau pour cadre, plateau en Bois, double face, piètements métalliques réglable, Dim. 1600×800×750, 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS1045', '3022', 'Bureau pour secrétaire 1,10x55x74 + 1 caisson de 2T avec serrure', 'Affecté', 'CAT_BUREAU'],
            ['IS0012', '4347', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0013', '4348', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0014', '4349', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0015', '4350', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0016', '4351', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0017', '4352', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0018', '4353', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0019', '4354', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS1810', '4345', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS1811', '4346', 'Bureau semi-métallique 1400x800x740 avec caissons à 3 tiroirs', 'Affecté', 'CAT_BUREAU'],
            ['IS0206', '4531', 'Bureau semi-métallique(LXPXH en mm :1400x800x740)', 'Affecté', 'CAT_BUREAU'],
            ['IS1241', '3537', 'Burette à huile', 'Disponible', 'CAT_BURETTE_HUILE'],
            ['IS1248', '3546', 'Burin plat', 'Réformé', 'CAT_BURIN'],
            ['IS1249', '3547', 'Burin plat', 'Réformé', 'CAT_BURIN'],
            ['IS0219', '4545', 'Burin plat  CARIOL', 'Réformé', 'CAT_BURIN'],
            ['IS0265', '4710', 'Burin plat CAPRIOL', 'Disponible', 'CAT_BURIN'],
            ['IS0267', '4711', 'Burin plat CAPRIOL', 'Disponible', 'CAT_BURIN'],
            ['IS1250', '3548', 'Burin pointu', 'Réformé', 'CAT_BURIN'],
            ['IS1252', '3549', 'Burin pointu', 'Réformé', 'CAT_BURIN'],
            ['IS0220', '4546', 'Burin pointu  CARIOL', 'Réformé', 'CAT_BURIN'],
            ['IS0050', '4382', 'Camera numérique SONY DVD', 'Réformé', 'CAT_CAMERA_NUM_RIQUE'],
            ['IS1559', '742', 'Canne à plomber', 'Réformé', 'CAT_CANNE_PLOMBER'],
            ['IS1570', '743', 'Canne à plomber', 'Réformé', 'CAT_CANNE_PLOMBER'],
            ['IS1581', '744', 'Chaîne d’arpenteur de 20 m', 'Réformé', 'CAT_CHA_NE_D_ARPENTEUR'],
            ['IS1592', '745', 'Chaîne d’arpenteur de 20 m', 'Réformé', 'CAT_CHA_NE_D_ARPENTEUR'],
            ['IS1049', '3030', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1050', '3031', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1051', '3032', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1052', '3033', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1054', '3034', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1055', '3035', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1056', '3036', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1057', '3037', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1058', '3038', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1059', '3039', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Réformé', 'CAT_CHAISE'],
            ['IS1060', '3040', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1061', '3041', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1062', '3042', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1063', '3043', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1065', '3044', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1066', '3045', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1067', '3046', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1068', '3047', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1069', '3048', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1070', '3049', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1071', '3050', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1072', '3051', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1073', '3052', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1074', '3053', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1076', '3054', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1077', '3055', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1078', '3056', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1079', '3057', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1080', '3058', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1081', '3059', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1082', '3060', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1083', '3061', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1084', '3062', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1085', '3063', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1087', '3064', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1088', '3065', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1089', '3066', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1090', '3067', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1091', '3068', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1092', '3069', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1093', '3070', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1094', '3071', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1095', '3072', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1096', '3073', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1098', '3074', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1099', '3075', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1100', '3076', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1101', '3077', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1102', '3078', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1103', '3079', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1104', '3080', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1105', '3081', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1106', '3082', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1107', '3083', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1109', '3084', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1110', '3085', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1111', '3086', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1112', '3087', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1113', '3088', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1114', '3089', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1115', '3090', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1116', '3091', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1117', '3092', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1118', '3093', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1120', '3094', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1121', '3095', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1122', '3096', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1123', '3097', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1124', '3098', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1125', '3099', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1126', '3100', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1127', '3101', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1128', '3102', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1129', '3103', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1131', '3104', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1132', '3105', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1133', '3106', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1134', '3107', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1135', '3108', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1136', '3109', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1137', '3110', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1138', '3111', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1139', '3112', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1140', '3113', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1142', '3114', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1143', '3115', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1144', '3116', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1145', '3117', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1146', '3118', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1147', '3119', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1148', '3120', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1149', '3121', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1150', '3122', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1151', '3123', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1153', '3124', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1154', '3125', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1155', '3126', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1156', '3127', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1157', '3128', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['IS1158', '3129', 'Chaise pliante tête et assise rembourrée Skai piétement métallique peint en Epoxy', 'Affecté', 'CAT_CHAISE'],
            ['AUTO_0245', null, 'Chaise étudiants type Mate ou son équivalent', 'Affecté', 'CAT_CHAISE'],
            ['AUTO_0246', null, 'Chaises Formateur', 'Affecté', 'CAT_CHAISE'],
            ['IS1308', '3676', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1309', '3677', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1310', '3678', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1311', '3679', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1312', '3680', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1313', '3681', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1314', '3682', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1315', '3683', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1316', '3684', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1318', '3686', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Disponible', 'CAT_CHAISE'],
            ['IS1319', '3687', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1320', '3688', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Affecté', 'CAT_CHAISE'],
            ['IS1321', '3689', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Disponible', 'CAT_CHAISE'],
            ['IS1322', '3690', 'Chaise roulante à 5 branches à gaz non basculant, en tissu avec accoudoir', 'Disponible', 'CAT_CHAISE'],
            ['IS0128', '4457', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0129', '4458', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0130', '4459', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0131', '4460', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0132', '4461', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0134', '4462', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0135', '4463', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0136', '4464', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0137', '4465', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0138', '4466', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0139', '4467', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0140', '4468', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0141', '4469', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0142', '4470', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0143', '4471', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0145', '4472', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0146', '4473', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0147', '4474', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0148', '4475', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0149', '4476', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0349', '4788', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0350', '4789', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0351', '4790', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0352', '4791', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0353', '4792', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0354', '4793', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0356', '4794', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0357', '4795', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0358', '4796', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0359', '4797', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0360', '4798', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0361', '4799', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0362', '4800', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0363', '4801', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Réformé', 'CAT_CHAISE'],
            ['IS0364', '4802', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Réformé', 'CAT_CHAISE'],
            ['IS0365', '4803', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0367', '4804', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0368', '4805', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0369', '4806', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0370', '4807', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0371', '4808', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0372', '4809', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0373', '4810', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0374', '4811', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0375', '4812', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0376', '4813', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0378', '4814', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0379', '4815', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0380', '4816', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0381', '4817', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0382', '4818', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0383', '4819', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0384', '4820', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0385', '4821', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0386', '4822', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0387', '4823', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0389', '4824', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0390', '4825', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0391', '4826', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0392', '4827', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0393', '4828', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0394', '4829', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0395', '4830', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0396', '4831', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0397', '4832', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0398', '4833', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0400', '4834', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0401', '4835', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0402', '4836', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique', 'Affecté', 'CAT_CHAISE'],
            ['IS0156', '4482', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0158', '4484', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0150', '4477', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0151', '4478', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0152', '4479', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0153', '4480', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0154', '4481', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0157', '4483', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0159', '4485', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0160', '4486', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0161', '4487', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0162', '4488', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0163', '4489', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0164', '4490', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0165', '4491', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0167', '4492', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0168', '4493', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0169', '4494', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0170', '4495', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS0171', '4496', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique, avec  tablette écritoire.', 'Affecté', 'CAT_CHAISE'],
            ['IS1777', '4315', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1778', '4316', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1780', '4317', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1781', '4318', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1782', '4319', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1783', '4320', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1784', '4321', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1785', '4322', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1786', '4323', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1787', '4324', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1788', '4325', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1789', '4326', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1791', '4327', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1792', '4328', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1793', '4329', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1794', '4330', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1795', '4331', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1796', '4332', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1797', '4333', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS1798', '4334', 'Chaise visiteur en polypropylène sur 4 pieds avec assise et dossier ironique.', 'Affecté', 'CAT_CHAISE'],
            ['IS0954', '495', 'Chaise visiteur en SKAI noir', 'Affecté', 'CAT_CHAISE'],
            ['IS0965', '496', 'Chaise visiteur en SKAI noir', 'Affecté', 'CAT_CHAISE'],
            ['IS0976', '497', 'Chaise visiteur en SKAI noir', 'Affecté', 'CAT_CHAISE'],
            ['IS0987', '498', 'Chaise visiteur en SKAI noir', 'Affecté', 'CAT_CHAISE'],
            ['IS0552', '4974', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0553', '4975', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0555', '4976', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0556', '4977', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0557', '4978', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0558', '4979', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0559', '4980', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0560', '4981', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0561', '4982', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0562', '4983', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Réformé', 'CAT_CHAISE'],
            ['IS0563', '4984', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0564', '4985', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0567', '4986', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0568', '4987', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0569', '4988', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0570', '4989', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0571', '4990', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0572', '4991', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0573', '4992', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0574', '4993', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0575', '4994', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0576', '4995', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0578', '4996', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0579', '4997', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Réformé', 'CAT_CHAISE'],
            ['IS0580', '4998', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0581', '4999', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0582', '5000', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0583', '5001', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0584', '5002', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['IS0585', '5003', 'Chaise visiteur en tissu noir, en polypropylène montée sur piètement luge', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1149_SEGMA', '1149/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1214_SEGMA', '1214/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1224_SEGMA', '1224/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1231_SEGMA', '1231/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1230_SEGMA', '1230/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1229_SEGMA', '1229/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1228_SEGMA', '1228/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1227_SEGMA', '1227/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1226_SEGMA', '1226/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1225_SEGMA', '1225/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1232_SEGMA', '1232/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1155_SEGMA', '1155/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1120_SEGMA', '1120/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1119_SEGMA', '1119/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1118_SEGMA', '1118/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1117_SEGMA', '1117/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1116_SEGMA', '1116/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1115_SEGMA', '1115/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1114_SEGMA', '1114/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1113_SEGMA', '1113/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1150_SEGMA', '1150/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1151_SEGMA', '1151/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1152_SEGMA', '1152/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1216_SEGMA', '1216/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1154_SEGMA', '1154/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1123_SEGMA', '1123/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1156_SEGMA', '1156/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1157_SEGMA', '1157/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1158_SEGMA', '1158/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1159_SEGMA', '1159/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1160_SEGMA', '1160/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1161_SEGMA', '1161/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1162_SEGMA', '1162/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1163_SEGMA', '1163/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1164_SEGMA', '1164/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1165_SEGMA', '1165/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1166_SEGMA', '1166/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1153_SEGMA', '1153/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1135_SEGMA', '1135/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1148_SEGMA', '1148/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1147_SEGMA', '1147/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1146_SEGMA', '1146/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1145_SEGMA', '1145/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1144_SEGMA', '1144/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1143_SEGMA', '1143/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1142_SEGMA', '1142/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1141_SEGMA', '1141/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1140_SEGMA', '1140/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1139_SEGMA', '1139/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1138_SEGMA', '1138/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1121_SEGMA', '1121/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1136_SEGMA', '1136/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1122_SEGMA', '1122/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1134_SEGMA', '1134/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1133_SEGMA', '1133/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1132_SEGMA', '1132/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1131_SEGMA', '1131/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1130_SEGMA', '1130/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1129_SEGMA', '1129/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1128_SEGMA', '1128/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1127_SEGMA', '1127/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1126_SEGMA', '1126/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1125_SEGMA', '1125/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1124_SEGMA', '1124/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1169_SEGMA', '1169/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1137_SEGMA', '1137/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1209_SEGMA', '1209/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1196_SEGMA', '1196/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1167_SEGMA', '1167/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1198_SEGMA', '1198/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1199_SEGMA', '1199/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1200_SEGMA', '1200/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1201_SEGMA', '1201/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1202_SEGMA', '1202/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1203_SEGMA', '1203/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1204_SEGMA', '1204/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1205_SEGMA', '1205/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1206_SEGMA', '1206/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1168_SEGMA', '1168/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1208_SEGMA', '1208/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1195_SEGMA', '1195/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1210_SEGMA', '1210/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1211_SEGMA', '1211/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1212_SEGMA', '1212/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1213_SEGMA', '1213/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1215_SEGMA', '1215/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1217_SEGMA', '1217/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1218_SEGMA', '1218/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1219_SEGMA', '1219/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1220_SEGMA', '1220/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1221_SEGMA', '1221/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1222_SEGMA', '1222/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1207_SEGMA', '1207/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1181_SEGMA', '1181/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1223_SEGMA', '1223/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1170_SEGMA', '1170/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1171_SEGMA', '1171/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1172_SEGMA', '1172/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1173_SEGMA', '1173/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1174_SEGMA', '1174/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1175_SEGMA', '1175/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1176_SEGMA', '1176/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1177_SEGMA', '1177/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1178_SEGMA', '1178/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1197_SEGMA', '1197/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1180_SEGMA', '1180/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1187_SEGMA', '1187/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1193_SEGMA', '1193/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1192_SEGMA', '1192/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1191_SEGMA', '1191/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1190_SEGMA', '1190/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1189_SEGMA', '1189/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1179_SEGMA', '1179/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1188_SEGMA', '1188/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1194_SEGMA', '1194/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1186_SEGMA', '1186/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1185_SEGMA', '1185/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1184_SEGMA', '1184/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1183_SEGMA', '1183/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['OLD_1182_SEGMA', '1182/SEGMA', 'CHAISES TYPE GATSBY', 'Affecté', 'CAT_CHAISE'],
            ['AUTO_0524', null, 'CHAISES ALLU ET ROTIN', 'Affecté', 'CAT_CHAISE'],
            ['IS1473', '3914', 'Chalumeau aéropropane', 'Disponible', 'CAT_CHALUMEAU'],
            ['IS0261', '4706', 'Chalumeau propane express NF', 'Disponible', 'CAT_CHALUMEAU'],
            ['OLD_1338_SEGMA', '1338/SEGMA', 'CHARIOT DESSERTE  SUR ROULETTE', 'Affecté', 'CAT_CHARIOT_DESSERTE_SUR'],
            ['IS1744', '4284', 'Charrue MF 765 A 2 Disques', 'Disponible', 'CAT_MAT_RIEL_TECHNIQUE'],
            ['OLD_1393_SEGMA', '1393/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1398_SEGMA', '1398/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1384_SEGMA', '1384/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1397_SEGMA', '1397/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1396_SEGMA', '1396/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1395_SEGMA', '1395/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1394_SEGMA', '1394/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1392_SEGMA', '1392/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1391_SEGMA', '1391/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1390_SEGMA', '1390/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1389_SEGMA', '1389/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1388_SEGMA', '1388/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1387_SEGMA', '1387/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1385_SEGMA', '1385/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1383_SEGMA', '1383/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1382_SEGMA', '1382/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1381_SEGMA', '1381/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['OLD_1386_SEGMA', '1386/SEGMA', 'CHAUFFE EAU AVEC CAPTEUR SOLAIRE', 'Affecté', 'CAT_CHAUFFE_EAU_AVEC_CAP'],
            ['IS1759', '4297', 'Cisaille à gazon à batterie Wolf SP45', 'Réformé', 'CAT_CISAILLE'],
            ['IS1760', '4298', 'Cisaille à gazon à batterie Wolf SP45', 'Réformé', 'CAT_CISAILLE'],
            ['IS1761', '4299', 'Cisaille à gazon à batterie Wolf SP75', 'Réformé', 'CAT_CISAILLE'],
            ['IS1762', '4300', 'Cisaille à gazon à batterie Wolf SP75', 'Réformé', 'CAT_CISAILLE'],
            ['IS0759', '5160', 'Cisaille P51', 'Disponible', 'CAT_CISAILLE'],
            ['IS0760', '5161', 'Cisaille P51', 'Disponible', 'CAT_CISAILLE'],
            ['IS0761', '5162', 'Cisaille P51', 'Disponible', 'CAT_CISAILLE'],
            ['IS0762', '5163', 'Cisaille P51', 'Disponible', 'CAT_CISAILLE'],
            ['IS0763', '5164', 'Cisaille P51', 'Disponible', 'CAT_CISAILLE'],
            ['IS0096', '4426', 'Cisaille PRADINE P 51', 'Réformé', 'CAT_CISAILLE'],
            ['IS0097', '4427', 'Cisaille PRADINE P 51', 'Réformé', 'CAT_CISAILLE'],
            ['IS0098', '4428', 'Cisaille PRADINE P 51', 'Réformé', 'CAT_CISAILLE'],
            ['IS0100', '4429', 'Cisaille PRADINE P 51', 'Affecté', 'CAT_CISAILLE'],
            ['IS0101', '4430', 'Cisaille PRADINE P 51', 'Affecté', 'CAT_CISAILLE'],
            ['IS0102', '4431', 'Cisaille PRADINE P 51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1517', '4027', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1518', '4028', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1519', '4029', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1520', '4030', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1521', '4031', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1522', '4032', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1523', '4033', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1524', '4034', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1525', '4035', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1527', '4036', 'Cisaille pradine P51', 'Réformé', 'CAT_CISAILLE'],
            ['IS1445', '3865', 'Ciseaux multifonction OAN  Wolf', 'Réformé', 'CAT_CISEAUX'],
            ['IS1446', '3866', 'Ciseaux multifonction OAN  Wolf', 'Réformé', 'CAT_CISEAUX'],
            ['IS1654', '4185', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1655', '4186', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1656', '4187', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1657', '4188', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1659', '4189', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1660', '4190', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1661', '4191', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1662', '4192', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1663', '4193', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS1664', '4194', 'Clapet métallique gris perle de 10 cases', 'Affecté', 'CAT_CLAPET'],
            ['IS0183', '4507', 'Classeur métallique à 4 tiroirs, format administratif.', 'Affecté', 'CAT_CLASSEUR'],
            ['IS0184', '4508', 'Classeur métallique à 4 tiroirs, format administratif.', 'Affecté', 'CAT_CLASSEUR'],
            ['IS0273', '4720', 'Clef à griffe 18’’ FACOM réf : 131 A', 'Disponible', 'CAT_CLEF_GRIFFE'],
            ['IS0258', '4702', 'Clef à griffe diam 18’’', 'Disponible', 'CAT_CLEF_GRIFFE'],
            ['IS0259', '4703', 'Clef à griffe diam 18’’', 'Disponible', 'CAT_CLEF_GRIFFE'],
            ['IS1469', '3911', 'Clef à griffe F 14’’', 'Disponible', 'CAT_CLEF_GRIFFE'],
            ['IS1468', '3910', 'Clef à griffe F 18’’', 'Disponible', 'CAT_CLEF_GRIFFE'],
            ['IS1727', '4263', 'Clef à Griffe type super EGO 24 ‘’', 'Disponible', 'CAT_CLEF_GRIFFE'],
            ['IS1728', '4264', 'Clef à Griffe type super EGO 24 ‘’', 'Réformé', 'CAT_CLEF_GRIFFE'],
            ['IS0274', '4721', 'Clef à moelette  10’’ FACOM réf : 113A', 'Disponible', 'CAT_CLEF_MOELETTE'],
            ['IS0448', '4879', 'Clef à moellette  Facom réf.12-113A', 'Réformé', 'CAT_CLEF_MOELETTE'],
            ['IS1236', '3531', 'Clef à moellette 8', 'Disponible', 'CAT_CLEF_MOELETTE'],
            ['IS1237', '3532', 'Clef à moellette14', 'Disponible', 'CAT_CLEF_MOELETTE'],
            ['IS1729', '4265', 'Clef à mollette 10’’ ACESA', 'Disponible', 'CAT_CLEF_MOELETTE'],
            ['IS1730', '4266', 'Clef à mollette 10’’ ACESA', 'Réformé', 'CAT_CLEF_MOELETTE'],
            ['IS0535', '4958', 'Climatiseur FITCO type PC 12000 BTU', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0536', '4959', 'Climatiseur FITCO type PC 18000 BTU', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0537', '4960', 'Climatiseur FITCO type PC 24000 BTU', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0534', '4957', 'Climatiseur FITCO type PC 9000 BTU', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0538', '4961', 'Climatiseur WHIRPOOL type 12000 BTU.', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0539', '4962', 'Climatiseur WHIRPOOL type 12000 BTU.', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0540', '4963', 'Climatiseur WHIRPOOL type 12000 BTU.', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0541', '4964', 'Climatiseur WHIRPOOL type 9000 BTU.', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS0542', '4965', 'Climatiseur WHIRPOOL type 9000 BTU.', 'Affecté', 'CAT_CLIMATISEUR'],
            ['IS1234', '3529', 'Coffre à outil métallique', 'Réformé', 'CAT_COFFRE_OUTIL_M_TALLI'],
            ['IS0266', '1294', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0277', '1295', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0288', '1296', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0299', '1297', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0310', '1298', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0321', '1299', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0332', '1300', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0344', '1301', 'Consigne (butane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0355', '1302', 'Consigne (butane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0366', '1303', 'Consigne (butane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0410', '1307', 'Consigne (butane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0421', '1308', 'Consigne (butane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0044', '1274', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0055', '1275', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0066', '1276', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0077', '1277', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0088', '1278', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0099', '1279', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0110', '1280', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0122', '1281', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0133', '1282', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0144', '1283', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0155', '1284', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0166', '1285', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0177', '1286', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0188', '1287', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0199', '1288', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0210', '1289', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0221', '1290', 'Consigne (propane)', 'Réformé', 'CAT_CONSIGNE_BUTANE'],
            ['IS0233', '1291', 'Consigne (propane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0244', '1292', 'Consigne (propane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0255', '1293', 'Consigne (propane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0377', '1304', 'Consigne (propane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0388', '1305', 'Consigne (propane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0399', '1306', 'Consigne (propane)', 'Disponible', 'CAT_CONSIGNE_BUTANE'],
            ['IS0846', '5238', 'Copieur /imprimante A4-A3 DEVELOP modèle INEO 284e', 'Affecté', 'CAT_COPIEUR_IMPRIMANTE'],
            ['IS0209', '4534', 'Copieur Rex Rotary MP 161', 'Réformé', 'CAT_COPIEUR_IMPRIMANTE'],
            ['IS0848', '5240', 'Ecran (pour Vidéo projecteur s) Manuel sur Trépied 200x200 Marque ORAY Modèle TRE1B1200200', 'Affecté', 'CAT_MATERIEL_P_DAGOGIQUE'],
            ['IS0195', '4520', 'Ecran de projection sur trépied, Dim : 1700x1700mm', 'Affecté', 'CAT_MATERIEL_P_DAGOGIQUE'],
            ['IS0895', '5283', 'Ecran Portable Manuel sur trépied Blanc Mat ( marque ORAY OU SIMILAIRE ): -Taille de l’image : 175x175cm-Format 4 :3-carter en tôle laquée noir', 'Affecté', 'CAT_MATERIEL_P_DAGOGIQUE'],
            ['IS0896', '5284', 'Ecran Portable Manuel sur trépied Blanc Mat ( marque ORAY OU SIMILAIRE ): -Taille de l’image : 175x175cm-Format 4 :3-carter en tôle laquée noir', 'Affecté', 'CAT_MATERIEL_P_DAGOGIQUE'],
            ['OLD_312_SEGMA', '312/SEGMA', 'Ecran pour vidéoprojecteur manuel de marque ORAY 2000 Pro Ecran sous carter en tôle acier laquéer blanc. SuRéformeace de projection blanc mat support mural 200x200cm', 'Disponible', 'CAT_MATERIEL_P_DAGOGIQUE'],
            ['OLD_313_SEGMA', '313/SEGMA', 'Ecran pour vidéoprojecteur manuel de marque ORAY 2000 Pro Ecran sous carter en tôle acier laquéer blanc. SuRéformeace de projection blanc mat support mural 200x200cm', 'Disponible', 'CAT_MATERIEL_P_DAGOGIQUE'],
            ['IS1337', '3725', 'Elagueur à enclume ref OR 86 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1338', '3726', 'Elagueur à enclume ref OR 86 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1340', '3727', 'Elagueur à enclume ref OR 86 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1341', '3728', 'Elagueur à enclume ref OR 86 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1342', '3730', 'Elagueur by - pass réf OS 82 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1343', '3731', 'Elagueur by - pass réf OS 82 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1344', '3732', 'Elagueur by - pass réf OS 82 WOLF', 'Réformé', 'CAT_ELAGUEUR'],
            ['IS1268', '3594', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1269', '3595', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1270', '3596', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1271', '3597', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1272', '3598', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1274', '3599', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1275', '3600', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1276', '3601', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1277', '3602', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1278', '3603', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1279', '3604', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1280', '3605', 'Equerre optique avec jalon télescopique', 'Réformé', 'CAT_EQUERRE'],
            ['IS1537', '740', 'Equerre optique double Kern', 'Réformé', 'CAT_EQUERRE'],
            ['IS1548', '741', 'Equerre optique double Kern', 'Réformé', 'CAT_EQUERRE'],
            ['IS0544', '4966', 'Extincteur 10Kg à poudre VALLEUNION.', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0545', '4967', 'Extincteur 10Kg à poudre VALLEUNION.', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0546', '4968', 'Extincteur 10Kg à poudre VALLEUNION.', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1814', '5300', 'Extincteur à eau pulvirisés avec additif de 6 litres', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1815', '5301', 'Extincteur à eau pulvirisés avec additif de 6 litres', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1816', '5302', 'Extincteur à eau pulvirisés avec additif de 6 litres', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1817', '5303', 'Extincteur à eau pulvirisés avec additif de 6 litres', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1818', '5304', 'Extincteur à eau pulvirisés avec additif de 6 litres', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1819', '5305', 'Extincteur à eau pulvirisés avec additif de 6 litres', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1160', '3206', 'Extincteur à P.P 10 Kg', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS1161', '3207', 'Extincteur à P.P 10 Kg', 'Réformé', 'CAT_EXTINCTEUR'],
            ['IS0275', '4722', 'Extincteur à poudre ABC de 6 kg', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0276', '4723', 'Extincteur à poudre ABC de 6 kg', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0278', '4724', 'Extincteur à poudre ABC de 6 kg', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0279', '4725', 'Extincteur à poudre ABC de 6 kg', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0280', '4726', 'Extincteur à poudre ABC de 6 kg', 'Affecté', 'CAT_EXTINCTEUR'],
            ['IS0020', '4355', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0021', '4356', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0023', '4357', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0024', '4358', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0025', '4359', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Réformé', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0026', '4360', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0027', '4361', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0028', '4362', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0029', '4363', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Réformé', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0030', '4364', 'Fauteuil de bureau en tissu sur roulettes réf : LN-03', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0207', '4532', 'Fauteuil de bureau en tissu sur roulettes, réf : LN – 03', 'Réformé', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0550', '4972', 'Fauteuil en tissu noir avec accoudoir, piètement sur 5 branches chromées, sur roulettes avec réglage hauteur d’assise', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0551', '4973', 'Fauteuil en tissu noir avec accoudoir, piètement sur 5 branches chromées, sur roulettes avec réglage hauteur d’assise', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1041', '3015', 'Fauteuil président en tissu 5 branches système à gaz pour table de réunion', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0205', '4530', 'Fauteuil président en tissu sur roulette', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['AUTO_0704', null, 'Fauteuil conférence', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['AUTO_0705', null, 'Fauteuil Podium', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1006', '2981', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1007', '2982', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1008', '2983', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1010', '2984', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1011', '2985', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1012', '2986', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1013', '2987', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1014', '2988', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Réformé', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1015', '2989', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1016', '2990', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1017', '2991', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1018', '2992', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1019', '2993', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1021', '2994', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1022', '2995', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1023', '2996', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Réformé', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1024', '2997', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1025', '2998', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1026', '2999', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1027', '3000', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1028', '3001', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1029', '3002', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS1030', '3003', 'Fauteuil visiteur en tissu non feu piétement luge avec accoudoir', 'Affecté', 'CAT_FAUTEUIL_DE_BUREAU'],
            ['IS0919', '1615', 'Fourche', 'Réformé', 'CAT_FOURCHE'],
            ['IS0920', '1616', 'Fourche', 'Réformé', 'CAT_FOURCHE'],
            ['IS0104', '4435', 'Fourche à 4 dents', 'Réformé', 'CAT_FOURCHE'],
            ['IS0105', '4436', 'Fourche à 4 dents', 'Réformé', 'CAT_FOURCHE'],
            ['IS0106', '4437', 'Fourche à 4 dents', 'Réformé', 'CAT_FOURCHE'],
            ['IS0107', '4438', 'Fourche à 4 dents', 'Réformé', 'CAT_FOURCHE'],
            ['IS0108', '4439', 'Fourche à 4 dents', 'Réformé', 'CAT_FOURCHE'],
            ['IS1300', '3669', 'Fourche à bêcher légère avec béquille AXT Wolf', 'Réformé', 'CAT_FOURCHE'],
            ['IS1301', '3670', 'Fourche à bêcher légère avec béquille AXT Wolf', 'Réformé', 'CAT_FOURCHE'],
            ['IS1302', '3671', 'Fourche à bêcher légère avec béquille AXT Wolf', 'Réformé', 'CAT_FOURCHE'],
            ['IS1303', '3672', 'Fourche à bêcher légère avec béquille AXT Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1304', '3673', 'Fourche à bêcher légère avec béquille AXT Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1417', '3827', 'Fourche à bêcher légère avec manche pommeau 1m avec repose-pied. Largeur 18cm. Hauteur 26cm AXO Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1418', '3828', 'Fourche à bêcher légère avec manche pommeau 1m avec repose-pied. Largeur 18cm. Hauteur 26cm AXO Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1419', '3829', 'Fourche à bêcher légère avec manche pommeau 1m avec repose-pied. Largeur 18cm. Hauteur 26cm AXO Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1420', '3830', 'Fourche à bêcher légère avec manche pommeau 1m avec repose-pied. Largeur 18cm. Hauteur 26cm AXO Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1421', '3831', 'Fourche à bêcher légère avec manche pommeau 1m avec repose-pied. Largeur 18cm. Hauteur 26cm AXO Wolf', 'Disponible', 'CAT_FOURCHE'],
            ['IS1422', '3832', 'Fourche à bêcher légère avec manche pommeau 1m avec repose-pied. Largeur 18cm. Hauteur 26cm AXO Wolf', 'Disponible', 'CAT_FOURCHE'],
        ];

        $catMap = DB::table('categories')->pluck('id', 'code_categorie')->toArray();

        foreach ($articles as [$ref, $ancien, $designation, $statut, $catCode]) {
            $catId = $catMap[$catCode] ?? null;
            if (! $catId) continue;

            DB::table('articles')->updateOrInsert(
                ['numero_reference' => $ref],
                [
                    'numero_reference' => $ref,
                    'code_ancien'      => $ancien,
                    'designation'      => $designation,
                    'statut'           => $statut,
                    'observations'     => null,
                    'categorie_id'     => $catId,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ]
            );
        }
    }
}
